#!/usr/bin/env python3
"""Generate video clips for each beat of a ZorkBurr recap.

Supports two video providers:
  - runway (default): Runway Gen-4 Turbo. Requires RUNWAY_KEY in .env.
    Duration: 5 or 10 seconds. No built-in audio.
  - veo: Google Veo 3.1 Lite. Requires GOOGLE_AI_STUDIO in .env.
    Duration: 4, 6, or 8 seconds. Built-in ambient audio.

Usage:
    uv run scripts/generate_recap_video.py --episode-id ep98 --all-beats --scene-stills
    uv run scripts/generate_recap_video.py --episode-id ep98 --all-beats --provider veo
    uv run scripts/generate_recap_video.py --episode-id ep98 --beat-index 3
    uv run scripts/generate_recap_video.py --episode-id ep98 --all-beats --dry-run
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from pathlib import Path

from google import genai
from google.genai import types

RECAPS_DIR = Path(__file__).parent.parent / "data" / "recaps"
CHARACTER_REFERENCE = RECAPS_DIR / "character_reference_cinematic_01.png"

# Base character description — the unchanging silhouette of the adventurer.
# This is a production constant, not an editorial decision. It gets prepended
# to every Veo prompt alongside the beat's inventory items.
# Must match the character reference image generated by
# scripts/generate_character_reference.py (STYLE_PROMPTS["cinematic"]).
BASE_CHARACTER = (
    "A lone adventurer in a worn brown travelling cloak with the hood "
    "raised, face half-concealed in shadow. Medium build, dark wool tunic, "
    "heavy trousers, mud-caked leather boots."
)

# --- Provider: Veo ---
VEO_MODEL_ID = "veo-3.1-lite-generate-preview"
VEO_VALID_DURATIONS = (4, 6, 8)
VEO_PRICE_PER_SECOND = {"720p": 0.05, "1080p": 0.08}

# --- Provider: Runway ---
RUNWAY_MODEL_ID = "gen4_turbo"
RUNWAY_VALID_DURATIONS = (5, 10)
RUNWAY_CREDITS_PER_SECOND = 5   # gen4_turbo = 5 credits/sec
RUNWAY_CREDIT_COST = 0.01       # $0.01 per credit

# --- Shared ---
NANO_BANANA_MODEL = "nano-banana-pro-preview"


def snap_duration(requested: int, provider: str) -> int:
    """Snap a requested duration up to the nearest valid value for the provider."""
    valid = VEO_VALID_DURATIONS if provider == "veo" else RUNWAY_VALID_DURATIONS
    clamped = max(min(requested, valid[-1]), valid[0])
    for v in valid:
        if clamped <= v:
            return v
    return valid[-1]

# Style enforcement directives, appended to every scene prompt.
#
# The Gemini API (unlike Vertex) does NOT support negative_prompt, so our
# only lever is aggressive positive prompting. Research on diffusion models
# shows "NOT X" / "no X" phrasing is a weak signal — the model often
# focuses on X anyway. These directives are written entirely in positive
# terms, describing what the shot IS with enough specificity and repetition
# that the target-style training-data neurons dominate the defaults.
#
# The --style flag picks which enforcer to use. The chosen enforcer also
# replaces the director's visual_style field at prompt-assembly time, so
# there is no conflict between director output and target style.
STYLE_ENFORCERS: dict[str, str] = {
    "cinematic": (
        "The entire shot is rendered as cinematic fantasy realism in the "
        "register of prestige television — The Witcher, Game of Thrones, "
        "House of the Dragon — or a AAA action RPG cutscene like God of War "
        "or The Last of Us. Shot on a virtual cinema camera with a 35mm "
        "equivalent lens, shallow depth of field, natural motivated lighting. "
        "Physical materials rendered with full PBR fidelity: the wool cloak "
        "shows individual fibers and weave, the leather boots show grain "
        "and scuffing, every surface has micro-detail. Grimdark colour "
        "grading: desaturated earth tones, muted greens and umbers, warm "
        "amber key light against cold blue shadow. Volumetric atmosphere, "
        "dust in the air catching the light. The character moves with the "
        "restrained, weighty physicality of live-action actors in costume. "
        "The overall look is that of a high-budget fantasy television still "
        "brought to motion — every frame could be a promotional key art."
    ),
    "painterly": (
        "The entire shot is rendered as a moving oil painting on rough "
        "canvas. Every frame shows visible brushstrokes, hand-painted "
        "textures, and the slight imperfection of traditional physical "
        "media. The colors are mixed on a wooden palette: burnt umber, raw "
        "sienna, yellow ochre, deep ultramarine, titanium white used "
        "sparingly. The figure and the setting are rendered with the loose, "
        "atmospheric brushwork of late-1970s fantasy paperback covers — "
        "Frank Frazetta, James Gurney, Darrell Sweet, Boris Vallejo, Jeff "
        "Jones. Every surface is painted, not rendered. The overall look "
        "is a 1979 fantasy paperback illustration that has been gently, "
        "softly animated — the painting breathes and moves but remains, "
        "unmistakably, a painting."
    ),
    "spiderverse": (
        "The entire shot is rendered in the visual style of Spider-Man: "
        "Into the Spider-Verse and Across the Spider-Verse — stylised "
        "cel-shaded 3D animation that looks like a moving comic book. "
        "Thick black ink outlines around the character and major shapes. "
        "Flat shaded colour regions — distinct steps of light and shadow, "
        "not smooth gradients. Visible halftone dot patterns in the "
        "mid-tones, giving a printed-comic feel. Slight chromatic "
        "aberration on high-contrast edges, with cyan and magenta fringes. "
        "Bold, saturated colours: warm ambers, deep purples, splashes of "
        "magenta. The camera moves with action-comic dynamism — every "
        "frame could be a panel in a printed graphic novel. The frame "
        "rate has the slightly stuttered feel of stop-motion, as though "
        "each pose was held for an extra half-beat."
    ),
}

POLL_INTERVAL_SECONDS = 10
POLL_TIMEOUT_SECONDS = 900  # 15 minutes


def _load_dotenv() -> None:
    """Load .env file into os.environ (uv run doesn't auto-load it)."""
    env_file = Path(__file__).parent.parent / ".env"
    if env_file.exists():
        for line in env_file.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                os.environ.setdefault(k.strip(), v.strip().strip("'\""))


def load_api_key(provider: str) -> str:
    _load_dotenv()
    if provider == "runway":
        for key in ("RUNWAY_KEY", "RUNWAYML_API_SECRET"):
            val = os.environ.get(key)
            if val:
                return val
        raise SystemExit(
            "No Runway API key found. Set RUNWAY_KEY in .env."
        )
    else:
        for key in ("GOOGLE_AI_STUDIO", "GOOGLE_API_KEY", "GEMINI_API_KEY"):
            val = os.environ.get(key)
            if val:
                return val
        raise SystemExit(
            "No Google AI Studio API key found. Set GOOGLE_AI_STUDIO in .env."
        )


def load_shot_list(episode_id: str) -> dict:
    path = RECAPS_DIR / f"{episode_id}.shotlist.json"
    if not path.exists():
        raise SystemExit(
            f"Shot list not found: {path}\n"
            f"Run: uv run scripts/generate_recap_script.py --episode-id {episode_id}"
        )
    return json.loads(path.read_text())


def load_reference_image(path: Path) -> types.Image:
    if not path.exists():
        raise SystemExit(
            f"Character reference image not found: {path}\n"
            f"Generate it with nano banana / your image tool and save it there, "
            f"or pass --character-reference PATH to point at a different file."
        )
    suffix = path.suffix.lower()
    mime = {"png": "image/png", "jpg": "image/jpeg", "jpeg": "image/jpeg",
            "webp": "image/webp"}.get(suffix.lstrip("."), "image/png")
    return types.Image(
        image_bytes=path.read_bytes(),
        mime_type=mime,
    )


# ---------------------------------------------------------------------------
# Per-beat scene still generation (nano banana)
# ---------------------------------------------------------------------------

def generate_scene_still(
    *,
    client: "genai.Client",
    character_reference_path: Path,
    beat: dict,
    shot_list: dict,
    style: str,
    out_path: Path,
) -> None:
    """Generate a scene-specific first frame for one beat via nano-banana-pro.

    Conditions on the canonical character reference image (so the adventurer's
    silhouette is preserved across beats) plus a textual scene description
    drawn from the beat's scene_prompt + carried_items. Output is a 16:9 still
    that Veo will use as the first frame of that beat's clip.
    """
    char_ref_bytes = character_reference_path.read_bytes()
    enforcer = STYLE_ENFORCERS[style]

    prompt = (
        f"Generate a single cinematic still frame in 16:9 landscape format. "
        f"This is the opening frame of a video clip — compose it as a "
        f"deliberate cinematic shot, framed and lit with intent.\n\n"
        f"Scene: {beat['scene_prompt']}\n\n"
        f"Character: {BASE_CHARACTER}\n\n"
        f"The character should look exactly like the figure in the input "
        f"reference image — same cloak, same hood, same proportions, same "
        f"silhouette, same face-in-shadow rendering — but placed into the "
        f"scene described above. Reuse the input image's character identity "
        f"verbatim; adapt only the setting and the carried gear.\n\n"
        f"Style enforcer: {enforcer}\n\n"
        f"This single still frame must look like it was captured from a "
        f"prestige fantasy television production. No text overlays, no UI, "
        f"no watermarks. 16:9 landscape."
    )

    response = client.models.generate_content(
        model=NANO_BANANA_MODEL,
        contents=[
            prompt,
            types.Part.from_bytes(data=char_ref_bytes, mime_type="image/png"),
        ],
        config=types.GenerateContentConfig(
            response_modalities=["TEXT", "IMAGE"],
        ),
    )

    image_bytes = None
    for cand in response.candidates:
        for part in cand.content.parts:
            inline = getattr(part, "inline_data", None)
            if inline and getattr(inline, "data", None):
                image_bytes = inline.data
                break
        if image_bytes:
            break

    if not image_bytes:
        raise SystemExit(
            f"nano banana returned no image for beat {beat['beat_index']}"
        )
    out_path.write_bytes(image_bytes)


# Runway caps promptText at 1000 characters. These condensed enforcers
# convey the same visual intent in ~150 chars instead of ~500.
RUNWAY_STYLE_ENFORCERS: dict[str, str] = {
    "cinematic": (
        "Cinematic fantasy realism. 35mm lens, shallow depth of field, "
        "natural lighting. Grimdark palette: desaturated earth tones, "
        "amber key light, blue shadow. Prestige television quality. "
        "No text, letters, numbers, subtitles, or watermarks in the frame."
    ),
    "painterly": (
        "Moving oil painting on canvas. Visible brushstrokes, hand-painted "
        "textures. 1970s fantasy paperback illustration style, softly animated. "
        "No text, letters, numbers, subtitles, or watermarks in the frame."
    ),
    "spiderverse": (
        "Spider-Verse cel-shaded animation style. Thick ink outlines, flat "
        "shaded colours, halftone dots, chromatic aberration. Bold saturated palette. "
        "No text, letters, numbers, subtitles, or watermarks in the frame."
    ),
}

RUNWAY_PROMPT_LIMIT = 1000


def _build_inventory_desc(beat: dict) -> str:
    if "inventory_at_start" in beat:
        items = beat["inventory_at_start"]
        return f"Carrying: {', '.join(items)}." if items else "Carrying nothing."
    elif "carried_items" in beat:
        return beat["carried_items"]
    return ""


def build_prompt(beat: dict, shot_list: dict, style: str, provider: str = "veo") -> str:
    """Assemble the video generation prompt.

    For Veo, uses the full style enforcer (~500 chars). For Runway, uses
    a condensed enforcer and truncates to 1000 chars total.
    """
    if provider == "runway":
        enforcer = RUNWAY_STYLE_ENFORCERS[style]
    else:
        enforcer = STYLE_ENFORCERS[style]

    inventory_desc = _build_inventory_desc(beat)

    parts = [
        beat["scene_prompt"],
        "",
        f"Character: {BASE_CHARACTER} {inventory_desc}",
        "",
        enforcer,
    ]
    prompt = "\n".join(parts)

    if provider == "runway" and len(prompt) > RUNWAY_PROMPT_LIMIT:
        # Trim scene_prompt to fit, keeping character + enforcer intact
        suffix = f"\n\nCharacter: {BASE_CHARACTER} {inventory_desc}\n\n{enforcer}"
        max_scene = RUNWAY_PROMPT_LIMIT - len(suffix) - 5
        scene = beat["scene_prompt"][:max_scene].rsplit(" ", 1)[0] + "..."
        prompt = scene + suffix

    return prompt


def pick_beat(shot_list: dict, beat_index: int) -> dict:
    beats = shot_list["beats"]
    match = [b for b in beats if b["beat_index"] == beat_index]
    if not match:
        available = [b["beat_index"] for b in beats]
        raise SystemExit(
            f"Beat {beat_index} not found in shot list. Available: {available}"
        )
    return match[0]


def _render_veo(
    client: "genai.Client",
    prompt: str,
    reference_path: Path,
    duration: int,
    resolution: str,
    aspect_ratio: str,
    out_path: Path,
    beat_index: int,
) -> None:
    """Call Veo 3.1 Lite and save the resulting mp4."""
    config = types.GenerateVideosConfig(
        aspect_ratio=aspect_ratio,
        resolution=resolution,
        duration_seconds=duration,
        number_of_videos=1,
    )

    print("Submitting Veo generation request...", file=sys.stderr)
    from google.genai import errors as _genai_errors
    for attempt in range(1, 6):
        try:
            operation = client.models.generate_videos(
                model=VEO_MODEL_ID,
                prompt=prompt,
                image=load_reference_image(reference_path),
                config=config,
            )
            break
        except _genai_errors.ClientError as e:
            if "RESOURCE_EXHAUSTED" in str(e) or "429" in str(e):
                wait = 60 * attempt
                print(
                    f"  [429] rate-limited — sleeping {wait}s then retrying "
                    f"(attempt {attempt}/5)",
                    file=sys.stderr,
                )
                time.sleep(wait)
                continue
            raise
    else:
        raise SystemExit(f"Gave up after 5 rate-limit retries on beat {beat_index}")

    start = time.time()
    while not operation.done:
        elapsed = int(time.time() - start)
        if elapsed > POLL_TIMEOUT_SECONDS:
            raise SystemExit(f"Polling timed out after {elapsed}s")
        print(f"  [{elapsed:>3}s] generating...", file=sys.stderr)
        time.sleep(POLL_INTERVAL_SECONDS)
        operation = client.operations.get(operation)
    elapsed = int(time.time() - start)
    print(f"  [{elapsed}s] complete.", file=sys.stderr)

    if hasattr(operation, "error") and operation.error:
        raise SystemExit(f"Generation failed on beat {beat_index}: {operation.error}")

    response = operation.response
    if not response or not getattr(response, "generated_videos", None):
        raise SystemExit(f"No video in response for beat {beat_index}: {response}")

    generated = response.generated_videos[0]
    client.files.download(file=generated.video)
    generated.video.save(str(out_path))


def _render_runway(
    client: "RunwayML",
    prompt: str,
    reference_path: Path,
    duration: int,
    out_path: Path,
    beat_index: int,
) -> None:
    """Call Runway Gen-4 Turbo image-to-video and save the resulting mp4."""
    import base64
    import httpx

    # Runway accepts base64 data URIs for prompt_image
    img_bytes = reference_path.read_bytes()
    suffix = reference_path.suffix.lower().lstrip(".")
    mime = {"png": "image/png", "jpg": "image/jpeg", "jpeg": "image/jpeg"}.get(suffix, "image/png")
    b64_uri = f"data:{mime};base64,{base64.b64encode(img_bytes).decode()}"

    print("Submitting Runway generation request...", file=sys.stderr)
    task = client.image_to_video.create(
        model=RUNWAY_MODEL_ID,
        prompt_image=b64_uri,
        prompt_text=prompt,
        ratio="1280:720",
        duration=duration,
    )

    start = time.time()
    print(f"  task id: {task.id}", file=sys.stderr)

    # Poll until complete
    while True:
        elapsed = int(time.time() - start)
        if elapsed > POLL_TIMEOUT_SECONDS:
            raise SystemExit(f"Polling timed out after {elapsed}s")
        task = client.tasks.retrieve(id=task.id)
        status = task.status
        if status == "SUCCEEDED":
            break
        elif status in ("FAILED", "CANCELLED"):
            failure = getattr(task, "failure", None) or "unknown"
            raise SystemExit(
                f"Runway generation failed on beat {beat_index}: {status} — {failure}"
            )
        print(f"  [{elapsed:>3}s] {status.lower()}...", file=sys.stderr)
        time.sleep(POLL_INTERVAL_SECONDS)

    elapsed = int(time.time() - start)
    print(f"  [{elapsed}s] complete.", file=sys.stderr)

    # Download the output video
    output_urls = task.output or []
    if not output_urls:
        raise SystemExit(f"No output URL in Runway task for beat {beat_index}")
    video_url = output_urls[0]
    resp = httpx.get(video_url)
    resp.raise_for_status()
    out_path.write_bytes(resp.content)


def render_beat(
    *,
    client,
    shot_list: dict,
    beat: dict,
    args: argparse.Namespace,
) -> float:
    """Render a single beat. Returns the estimated cost billed."""
    beat_index = beat["beat_index"]
    provider = args.provider

    requested_duration = beat["duration_seconds"]
    duration = snap_duration(requested_duration, provider)
    valid_set = VEO_VALID_DURATIONS if provider == "veo" else RUNWAY_VALID_DURATIONS
    if duration != requested_duration:
        print(
            f"  ⚠ Beat {beat_index} duration {requested_duration}s snapped to "
            f"{duration}s ({provider} accepts {valid_set}).",
            file=sys.stderr,
        )

    prompt = build_prompt(beat, shot_list, args.style, provider)

    if provider == "veo":
        cost = duration * VEO_PRICE_PER_SECOND[args.resolution]
        model_name = VEO_MODEL_ID
    else:
        cost = duration * RUNWAY_CREDITS_PER_SECOND * RUNWAY_CREDIT_COST
        model_name = RUNWAY_MODEL_ID

    out_path = args.out_dir / f"{args.episode_id}.beat{beat_index:02d}.{args.style}.mp4"

    print("=" * 72, file=sys.stderr)
    print(f"Episode:     {args.episode_id}", file=sys.stderr)
    print(f"Beat:        {beat_index}/{len(shot_list['beats'])} — {beat['title']}", file=sys.stderr)
    print(f"Turn range:  {beat['turn_range']}", file=sys.stderr)
    print(f"Duration:    {duration}s  (requested {requested_duration}s)", file=sys.stderr)
    print(f"Provider:    {provider}", file=sys.stderr)
    print(f"Style:       {args.style}", file=sys.stderr)
    print(f"Reference:   {args.character_reference.name}", file=sys.stderr)
    print(f"Model:       {model_name}", file=sys.stderr)
    print(f"Cost est:    ${cost:.3f}", file=sys.stderr)
    print(f"Output:      {out_path.name}", file=sys.stderr)
    print("=" * 72, file=sys.stderr)

    if args.verbose_prompt:
        print(f"\nPROMPT:\n{prompt}\n", file=sys.stderr)
        print("=" * 72, file=sys.stderr)

    if client is None:
        print("(dry-run — not calling the API)\n", file=sys.stderr)
        return 0.0

    if out_path.exists() and args.skip_existing:
        print(f"(already exists — skipping: {out_path.name})\n", file=sys.stderr)
        return 0.0

    if provider == "veo":
        _render_veo(
            client=client, prompt=prompt, reference_path=args.character_reference,
            duration=duration, resolution=args.resolution,
            aspect_ratio=args.aspect_ratio, out_path=out_path, beat_index=beat_index,
        )
    else:
        _render_runway(
            client=client, prompt=prompt, reference_path=args.character_reference,
            duration=duration, out_path=out_path, beat_index=beat_index,
        )

    size_mb = out_path.stat().st_size / (1024 * 1024)
    print(f"Saved {size_mb:.1f} MB -> {out_path}\n", file=sys.stderr)
    return cost


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--episode-id", required=True, help="e.g. ep98")
    parser.add_argument("--beat-index", type=int, default=None,
                        help="Beat number to render (1-based). Required unless --all-beats is set.")
    parser.add_argument("--all-beats", action="store_true",
                        help="Render every beat in the shot list sequentially. "
                             "Skips beats whose output file already exists (use "
                             "--no-skip-existing to force).")
    parser.add_argument("--chain-beats", action="store_true",
                        help="With --all-beats: use each beat's last frame as the "
                             "first-frame conditioning image for the next beat. "
                             "Only works for shot lists where adjacent beats are in "
                             "adjacent locations — incompatible with most recaps.")
    parser.add_argument("--scene-stills", action="store_true",
                        help="Generate a per-beat scene-specific first frame using "
                             "nano-banana-pro (conditioned on --character-reference) "
                             "before each Veo call. Recommended when adjacent beats "
                             "are in unrelated locations. Mutually exclusive with "
                             "--chain-beats.")
    parser.add_argument("--no-skip-existing", dest="skip_existing",
                        action="store_false", default=True,
                        help="With --all-beats, regenerate beats even if output exists.")
    parser.add_argument("--resolution", default="720p", choices=["720p", "1080p"])
    parser.add_argument("--aspect-ratio", default="16:9", choices=["16:9", "9:16"])
    parser.add_argument("--dry-run", action="store_true",
                        help="Print the prompt and cost estimate, don't call the API")
    parser.add_argument("--verbose-prompt", action="store_true",
                        help="Print the full assembled prompt for each beat")
    parser.add_argument("--out-dir", type=Path, default=RECAPS_DIR)
    parser.add_argument(
        "--character-reference",
        type=Path,
        default=CHARACTER_REFERENCE,
        help="Path to the character reference image",
    )
    parser.add_argument(
        "--style",
        choices=sorted(STYLE_ENFORCERS.keys()),
        default="cinematic",
        help="Visual style enforcer to append to the prompt (default: cinematic)",
    )
    parser.add_argument(
        "--provider",
        choices=["runway", "veo"],
        default="runway",
        help="Video generation provider (default: runway)",
    )
    args = parser.parse_args()

    if not args.all_beats and args.beat_index is None:
        parser.error("Either --beat-index N or --all-beats is required.")
    if args.chain_beats and args.scene_stills:
        parser.error("--chain-beats and --scene-stills are mutually exclusive.")

    args.out_dir.mkdir(parents=True, exist_ok=True)
    shot_list = load_shot_list(args.episode_id)

    # Select which beats to render
    if args.all_beats:
        beats_to_render = shot_list["beats"]
    else:
        beats_to_render = [pick_beat(shot_list, args.beat_index)]

    # Instantiate client(s) only in live mode
    client = None
    google_client = None  # needed for scene stills (nano-banana) even with Runway
    if not args.dry_run:
        api_key = load_api_key(args.provider)
        if args.provider == "runway":
            from runwayml import RunwayML
            client = RunwayML(api_key=api_key)
        else:
            client = genai.Client(api_key=api_key)

        # Scene stills always use Google's nano-banana, regardless of video provider
        if args.scene_stills:
            _load_dotenv()
            for gkey in ("GOOGLE_AI_STUDIO", "GOOGLE_API_KEY", "GEMINI_API_KEY"):
                gval = os.environ.get(gkey)
                if gval:
                    google_client = genai.Client(api_key=gval)
                    break

    total_cost = 0.0
    initial_reference = args.character_reference  # preserve for the log header
    for beat_loop_idx, beat in enumerate(beats_to_render):
        beat_idx = beat["beat_index"]

        # Inter-beat delay to avoid rate limiting. Runway is more lenient
        # than Veo but a brief pause prevents 429 storms on either provider.
        if beat_loop_idx > 0 and not args.dry_run:
            time.sleep(5 if args.provider == "runway" else 15)

        if args.chain_beats and beat_idx > 1:
            prev_chain_frame = args.out_dir / f".chain_frame_beat{beat_idx - 1:02d}.png"
            if prev_chain_frame.exists():
                args.character_reference = prev_chain_frame
            else:
                print(
                    f"  ⚠ chain: previous frame {prev_chain_frame.name} missing, "
                    f"falling back to {initial_reference.name}",
                    file=sys.stderr,
                )
                args.character_reference = initial_reference

        if args.scene_stills:
            scene_still_path = (
                args.out_dir
                / f"{args.episode_id}.beat{beat_idx:02d}.scenestill.png"
            )
            if scene_still_path.exists() and args.skip_existing:
                print(
                    f"  scene still: cached {scene_still_path.name}",
                    file=sys.stderr,
                )
            elif (google_client or client) is not None:
                still_client = google_client or client
                print(
                    f"  scene still: generating {scene_still_path.name} via "
                    f"{NANO_BANANA_MODEL}...",
                    file=sys.stderr,
                )
                generate_scene_still(
                    client=still_client,
                    character_reference_path=initial_reference,
                    beat=beat,
                    shot_list=shot_list,
                    style=args.style,
                    out_path=scene_still_path,
                )
            args.character_reference = scene_still_path

        total_cost += render_beat(
            client=client, shot_list=shot_list, beat=beat, args=args,
        )

        # If chaining, extract the last frame of this beat for the next one —
        # even if we skipped a regeneration (so the chain survives reruns).
        if args.chain_beats:
            out_path = (
                args.out_dir
                / f"{args.episode_id}.beat{beat_idx:02d}.{args.style}.mp4"
            )
            chain_frame = args.out_dir / f".chain_frame_beat{beat_idx:02d}.png"
            if out_path.exists():
                subprocess.run(
                    ["ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
                     "-sseof", "-0.1", "-i", str(out_path),
                     "-vframes", "1", str(chain_frame)],
                    check=True,
                )
            else:
                print(
                    f"  ⚠ chain: beat {beat_idx} output missing, chain broken",
                    file=sys.stderr,
                )

    print("=" * 72, file=sys.stderr)
    print(f"Rendered {len(beats_to_render)} beat(s). Actual cost: ${total_cost:.3f}",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
